name: workflow-api

on: pull_request

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.x"

            - name: Build Docker image
              run: docker build -t api-loja .

            - name: Run Docker container
              run: docker run -d --name api-loja -p 5002:5002 api-loja

            - name: Create environment variable file
              run: |
                  touch .env
                  echo "${{ secrets.ENV_FILE }}" > .env
